### ISSUE TITLE
[Question] How do I get game IDs?

### ISSUE THREAD

**Issue by Bruniiin** [FlavioFS/ParsecSoda#4]
I'd like to know if there is a legal way for me to see them, thanks ^^

**Comment by FlavioFS** [comment]
Yes, there is.

### Short answer
HTTP Request to Parsec API asking for public room list. (yes, a bit thechnical but no coding skills required)

### Long answer
There is no way to do it through Soda yet, because we cannot disclose game id information due to Parsec SDK license. I'm going to post a video tutorial on how to find game ids on my Youtube channel, though.

I'm also considering a window that let's you save the thumbnails from public rooms so you can use them later, the only reason this doesn't exist yet is that I'm worried about the legal impacts of that feature.

**Comment by Bruniiin** [comment]
That's good to know, thank you
